workflows:
  ios-release:
    name: "iOS Release Build"
    max_build_duration: 60

    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
      groups:
        - app

    scripts:
      - name: Install dependencies
        script: |
          flutter pub get

      - name: Build iOS Release
        script: |
          flutter build ipa --release --no-codesign

    artifacts:
      - build/ios/ipa/*.ipa

    publishing:
      app_store_connect:
        key_id: $APP_STORE_CONNECT_KEY_IDENTIFIER
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID
        api_key: $APP_STORE_CONNECT_API_KEY
        submit_to_testflight: true
