workflows:
  ios-release:
    name: "iOS Release Build"
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
      vars:
        DEVELOPMENT_TEAM: "TNN6AXVF42"   # ← مهم جداً لحل مشكلة البيلد
        APPSTORE_API_KEY: $APPSTORE_API_KEY

    scripts:
      - name: Install dependencies
        script: |
          flutter pub get

      - name: Build iOS Release
        script: |
          flutter build ipa --release --codesign

    artifacts:
      - build/ios/ipa/*.ipa

    publishing:
      app_store_connect:
        api_key: $APPSTORE_API_KEY
        key_id: "L75442LLY"
        issuer_id: "26d221d5-8e05-4afb-9981-384cf9e02dd0"
        submit_to_testflight: true
